name: centos-base

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer
    

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: fix
          target: centos-base.json

      # validate templates
      - name: Validate Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: centos-base.json
      - name: echo pwd
        run: | 
          echo $PWD
          ls -la
      - name: echo pwd
        working-directory: /
        run: | 
          echo $PWD
          ls -la

      # build artifact
      - name: Build Artifact
        uses: ./.github/actions/packer/
<<<<<<< HEAD
=======
        working-directory: /root
>>>>>>> 1deec29023049f3355cf6cee1c10d50c752c5f3f
        env:
          UPCLOUD_API_PASSWORD: ${{ secrets.UPCLOUD_API_PASSWORD }}
          UPCLOUD_API_USER: ${{ secrets.UPCLOUD_API_USER }}
          PACKER_CONFIG_DIR: /opt
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: centos-base.json
