name: 'CentOS 8 base images'

on:
  push:

jobs:
  upcloud:
    runs-on: ubuntu-latest
    name: 'Upcloud: CentOS 8 base image'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fix Packer Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: fix
          target: centos-base-upcloud.json

      - name: Validate Packer Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: centos-base-upcloud.json

      - name: Build CentOS VM
        uses: ./.github/actions/packer/
        env:
          UPCLOUD_API_PASSWORD: ${{ secrets.UPCLOUD_API_PASSWORD }}
          UPCLOUD_API_USER: ${{ secrets.UPCLOUD_API_USER }}
          PACKER_CONFIG_DIR: /opt
          PACKER_LOG: 1
          PACKER_LOG_PATH: packer-logs
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: centos-base-upcloud.json
      - name: Export Storage UUID
        run: cat packer-logs | grep "upcloud: Private" | cut -d ' ' -f 9 | cut -d ',' -f 1 > upcloud-centos-base-image-uuid
      - uses: actions/upload-artifact@v2
        with:
          name: upcloud-centos-base-image-uuid
          path: ./upcloud-centos-base-image-uuid
