name: 'ssh test'

on:
  push:

jobs:
  centos_base:
    runs-on: ubuntu-latest
    name: 'ssh test'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Store SSH keys
        env:
          PUB: "${{ secrets.PUBLIC_SSH_KEY }}" 
          PRI: "${{ secrets.PRIVATE_SSH_KEY }}"
        run: | 
          "echo ${{ env.PUB }} > id_rsa.pub"
          "echo ${{ env.PRI }} > id_rsa"


